export const GLAV_ROUTE = '/'
export const OOMPANII_ROUTER = '/info'
export const USLUGI_ROUTER = '/uslugi'
export const EXPERTIZA_ROUTER = '/expertiza'
export const POJECTS_ROUTER = '/projects'
export const POJECTS_SHABLON_ROUTER = '/Project_shablon'
export const KONTACTS_ROUTE = '/kontacts'